### ISSUE TITLE
Server To-Do

### ISSUE THREAD

**Issue by jalovatt** [jalovatt/where-on-wikipedia#4]
- [ ] Refactor + split into modules
- [ ] Make sure login/cookie/etc stuff is being handled and returned correctly
- [ ] Game routes
  - [ ] Make a dummy page to play the game with
  - [ ] /game/new
    - Generate new game, return an ID and the first step
    - For now, will use a pre-generated game
  - [ ] /game/search
    - Given a game ID and step (article title/ID), return clue X
    - Generate a new clue each time rather than pre-generating them?
      - Would this require fresh Wiki queries?
    - If the last step, return either a message that the thief is near or prompt for the player to capture them
  - [ ] /game/capture
    - Given a game ID, step, and (hopefully) a warrant, handle end-game logic
- [ ] Move game storage from active memory into MongoDB
- [ ] Bring in (and refactor) Wikipedia queries
- [ ] Let the server generate new games instead of using the pre-built one
